name: Build & Test CompositeA

on:
  pull_request:
    branches: ['main']
  workflow_dispatch: {}

jobs:    
  Build-And-Test-CompositeA:
    runs-on: ubuntu-22.04    
    timeout-minutes: 15
    steps:
      - name: Print GitHub Environment
        run: echo '${{ toJSON(github) }}'
      - name: Print Environment Variables
        run: env | sort
      - name: Checkout CompositeA
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: 'Report on Submodules'
        run: |
          set -x -e -o pipefail
          exec 2>&1
          git submodule foreach 'set -x && pwd && git status && git log -n 5'
      - name: Generate GitHub App Token
        id: generate_token
        uses: tibdex/github-app-token@v1.7.0
        with:
          app_id: ${{ secrets.AUTH_APP_ID }}
          private_key: ${{ secrets.AUTH_APP_PRIVATE_KEY }}
      - name: 'Notify componentA of compositeA check start'
        uses: LouisBrunner/checks-action@v1.6.0
        with:
          sha: ${{ fromJSON(github.event.pull_request.body).component_pr.sha }}
          token: ${{ steps.generate_token.outputs.token }}
          name: 'CompositeA: Build & Test CompositeA'
          repo: 'opensafety/componentA'
          status: 'in_progress'
          details_url: 'https://www.github.com/opensafety/compositeA/actions/runs/${{ github.run_id }}'
