name: Build & Test CompositeA

on:
  pull_request:
  merge_group:
    types:
      - checks_requested
    branches:
      - main

jobs:    
  Build-And-Test-CompositeA:
    runs-on: ubuntu-22.04    
    timeout-minutes: 15
    if: github.event_name == 'merge_group'
    steps:
      - name: Print GitHub Environment
        run: echo '${{ toJSON(github) }}'
      - name: Print Environment Variables
        run: env | sort
      - name: Checkout CompositeA
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: 'Report on Submodules'
        id: submodules_info
        run: |
          set -x -e -o pipefail
          exec 2>&1
          git submodule foreach 'set -x && pwd && git status && git log -n 5'
          echo MERGED_COMMIT_MESSAGE=`git show HEAD^2 --format=%s --no-patch` | tee -a $GITHUB_OUTPUT | jq -C .
      - name: Generate GitHub App Token
        id: generate_token
        uses: tibdex/github-app-token@v1.7.0
        with:
          app_id: ${{ secrets.AUTH_APP_ID }}
          private_key: ${{ secrets.AUTH_APP_PRIVATE_KEY }}
      - name: 'Notify componentA of compositeA check start'
        uses: LouisBrunner/checks-action@v1.6.0
        id: check_start
        with:
          #sha: ${{ fromJSON(github.event.pull_request.body).component_pr.sha }}
          sha: ${{ fromJSON(steps.submodules_info.outputs.MERGED_COMMIT_MESSAGE).component_pr.sha }}
          token: ${{ steps.generate_token.outputs.token }}
          name: 'CompositeA: Build & Test CompositeA'
          repo: 'opensafety/componentA'
          status: 'in_progress'
          details_url: 'https://www.github.com/opensafety/compositeA/actions/runs/${{ github.run_id }}'

      - name: 'Actually Do:  Build & Test CompositeA'
        run: |
          set -x -e -o pipefail
          exec 2>&1
          echo Hello world!!
          sleep 2
          echo Bie-bye world!!
      - name: 'Notify self: waiting for component to finish other checks..'
        uses: LouisBrunner/checks-action@v1.6.0
        id: component_ready
        with:
          sha: ${{ github.sha }}
          token: ${{ steps.generate_token.outputs.token }}
          name: 'Component Ready'
          status: 'in_progress'

      - name: 'Notify component of composite check finish'
        uses: LouisBrunner/checks-action@v1.6.0
        with:
          check_id: ${{ steps.check_start.outputs.check_id }}
          token: ${{ steps.generate_token.outputs.token }}
          repo: 'opensafety/componentA'
          status: completed
          conclusion: success
          # In case, the action was re-run, update the details link to the last instance...
          details_url: 'https://www.github.com/opensafety/compositeA/actions/runs/${{ github.run_id }}'
          # Let parent know what to report on when ready...
          output: ${{toJSON(steps.component_ready.outputs)}}
